# Generated by Django 6.0.3 on 2026-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_carousel_carouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
